<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mk8.Drava.Registration</RootNamespace><IsPackable>true</IsPackable></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../mk8.drava.Contracts/mk8.drava.Contracts.csproj" />
    <ProjectReference Include="../mk8.drava.Configuration/mk8.drava.Configuration.csproj" />
    <ProjectReference Include="../mk8.drava.Transport/mk8.drava.Transport.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
  </ItemGroup>
</Project>
