using System.Globalization;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mk8.Drava.BuildTools;

public sealed class AnnotateDravaProtocol : Microsoft.Build.Utilities.Task
{
    private const string Marker = "// mk8.drava: nullable protocol signatures v1\n";
    [Required]
    public string MessagesFile { get; set; } = "";
    [Required]
    public string ServicesFile { get; set; } = "";

    public override bool Execute()
    {
        AnnotateFile(MessagesFile);
        AnnotateFile(ServicesFile);
        return true;
    }

    private static void AnnotateFile(string path)
    {
        var source = File.ReadAllText(path);
        if (source.StartsWith(Marker, StringComparison.Ordinal)) return;
        if (source.Length > 1_000_000 || !source.Contains("<auto-generated>", StringComparison.Ordinal) || !source.Contains("drava.proto", StringComparison.Ordinal))
            throw new InvalidDataException("Unexpected protocol generator output.");
        var root = CSharpSyntaxTree.ParseText(source).GetRoot();
        var messages = new HashSet<string>(StringComparer.Ordinal);
        foreach (var node in root.DescendantNodes())
            if (node is ClassDeclarationSyntax declaration) messages.Add(declaration.Identifier.ValueText);
        var annotated = new ProtocolNullableAnnotator(messages).Visit(root) ?? throw new InvalidDataException("Protocol syntax is missing.");
        if (!string.Equals(Fingerprint(root), Fingerprint(annotated), StringComparison.Ordinal))
            throw new InvalidDataException("Protocol annotation changed tokens other than nullable type annotations.");
        File.WriteAllText(path, Marker + "#nullable enable annotations\n" + annotated.ToFullString());
    }

    private static string Fingerprint(SyntaxNode node)
    {
        var erased = new EraseNullable().Visit(node) ?? throw new InvalidDataException("Protocol syntax is missing.");
        var text = new StringBuilder();
        foreach (var token in erased.DescendantTokens())
            text.Append(token.RawKind.ToString(CultureInfo.InvariantCulture)).Append(':').Append(token.Text).Append('\n');
        return text.ToString();
    }

    private sealed class EraseNullable : CSharpSyntaxRewriter
    {
        public override SyntaxNode? VisitNullableType(NullableTypeSyntax node) => Visit(node.ElementType);
    }
}
