<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mk8.Drava.BuildTools</RootNamespace></PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Build.Framework"><HintPath>$(MSBuildToolsPath)/Microsoft.Build.Framework.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Microsoft.Build.Utilities.Core"><HintPath>$(MSBuildToolsPath)/Microsoft.Build.Utilities.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Microsoft.CodeAnalysis"><HintPath>$(MSBuildToolsPath)/Roslyn/bincore/Microsoft.CodeAnalysis.dll</HintPath></Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp"><HintPath>$(MSBuildToolsPath)/Roslyn/bincore/Microsoft.CodeAnalysis.CSharp.dll</HintPath></Reference>
  </ItemGroup>
</Project>
