namespace Mk8.Drava.Contracts.Administration.V1;
public sealed record ProxySubsystemSummariesResponse(ProxyConfigSubsystemSummaryResponse Config, ProxyListenerSubsystemSummaryResponse Listeners, ProxyRouteSubsystemSummaryResponse Routes, ProxyCertificateSubsystemSummaryResponse Certificates, ProxyAcmeSubsystemSummaryResponse Acme, ProxyUpstreamSubsystemSummaryResponse Upstreams, ProxyCacheSubsystemSummaryResponse Cache, ProxyCircuitSubsystemSummaryResponse Circuits, ProxyLimitSubsystemSummaryResponse Limits, ProxyLogSubsystemSummaryResponse Logs, ProxyShutdownSubsystemSummaryResponse Shutdown, ProxyProtocolSubsystemSummaryResponse Protocols)
{
}
