<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mk8.Drava.IntegrationTests</RootNamespace><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../mk8.drava.Registration/mk8.drava.Registration.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../mk8.drava.Application/mk8.drava.Application.csproj" />
    <ProjectReference Include="../mk8.drava.Gateway/mk8.drava.Gateway.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.analyzers" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
