<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mk8.Drava.ArchitectureTests</RootNamespace><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.analyzers" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
